MAXCHOICES = 3      # max wishlist choices

# Constants for Student columns
WISHLIST0 = 0
WISHLIST1 = 1
WISHLIST2 = 2
ASSIGNED = 3
RANKRCVD = 4
EMAIL = 5
GRADE = 6

# Constants for Position columns
POSID = 0
COMPANY = 1
SLOTSAVAIL = 2
FSTCHOICE = 3
SNDCHOICE = 4
THRDCHOICE = 5
ALLOCCOUNT = 6
REMAININGSLOTS = 7